upgrade_lite_device:
  name: Upgrade Lite Device
  description: Upgrade a Mysa Lite device to a Full features device.
  fields:
    device_id:
      name: Device ID
      description: The Home Assistant device ID of the Mysa device.
      required: true
      selector:
        device:
          integration: mysa

downgrade_lite_device:
  name: Downgrade Lite Device
  description: Revert an upgraded Mysa device back to its Lite model.
  fields:
    device_id:
      name: Device ID
      description: The Home Assistant device ID of the Mysa device.
      required: true
      selector:
        device:
          integration: mysa

killer_ping:
  name: Killer Ping
  description: Force a device to reboot into pairing mode. WARNING - requires re-pairing.
  fields:
    device_id:
      name: Device ID
      description: The Home Assistant device ID of the Mysa device.
      required: true
      selector:
        device:
          integration: mysa
